package com.ncs.entity;
// Generated Sep 16, 2017 12:12:51 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AmActionHistory generated by hbm2java
 */
@Entity
@Table(name = "am_action_history")
public class AmActionHistory implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private int id;
	private String userName;
	private String action;
	private String module;
	private Date dateAction;
	private String detailAction;
	private String detailAction1;
	private String recordId;
	private String product;
	private String category;
	private String account;
	private String manufacturer;
	private String manipulation;
	private String status;
	public AmActionHistory() {
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "action_history_id", unique = true, nullable = false, precision = 22, scale = 0)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "user_name", length = 100)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "action", length = 200)
	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	@Column(name = "module", length = 200)
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	@Column(name = "date_action")
	public Date getDateAction() {
		return this.dateAction;
	}

	public void setDateAction(Date dateAction) {
		this.dateAction = dateAction;
	}

	@Column(name = "detail_action", length = 1000)
	public String getDetailAction() {
		return this.detailAction;
	}

	public void setDetailAction(String detailAction) {
		this.detailAction = detailAction;
	}

	@Column(name = "record_id", length = 50)
	public String getRecordId() {
		return recordId;
	}

	public void setRecordId(String recordId) {
		this.recordId = recordId;
	}

	@Basic
	@Column(name = "product")
	public String getProduct() {
		return product;
	}

	public void setProduct(String product) {
		this.product = product;
	}

	@Basic
	@Column(name = "account")
	public String getAccount() {
		return account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	@Basic
	@Column(name = "category")
	public String getCategory() {
		return category;
	}

	public void setCategory(String category) {
		this.category = category;
	}
	
	
	@Basic
	@Column(name = "manufacturer")
	public String getManufacturer() {
		return manufacturer;
	}

	public void setManufacturer(String manufacturer) {
		this.manufacturer = manufacturer;
	}

	@Basic
	@Column(name = "manipulation")
	public String getManipulation() {
		return manipulation;
	}

	public void setManipulation(String manipulation) {
		this.manipulation = manipulation;
	}


	@Basic
	@Column(name = "status")
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Basic
	@Column(name = "detail_action1", length = 1000)
	public String getDetailAction1() {
		return detailAction1;
	}

	public void setDetailAction1(String detailAction1) {
		this.detailAction1 = detailAction1;
	}
}

